# Generated by Django 4.0.6 on 2022-07-25 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_name', models.CharField(max_length=255)),
                ('pet_type', models.CharField(choices=[('cat', 'cat'), ('dog', 'dog'), ('bird', 'bird')], max_length=15, verbose_name='Select Pet Type')),
                ('owner_name', models.CharField(max_length=255, verbose_name='Owner Name')),
                ('owner_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Owner Address')),
                ('owner_phone_number', models.CharField(default='', max_length=11, verbose_name='phone')),
            ],
        ),
    ]
