# Generated by Django 4.0.6 on 2022-08-11 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_name', models.CharField(max_length=255)),
                ('pet_type', models.CharField(choices=[('cat', 'cat'), ('dog', 'dog'), ('bird', 'bird')], max_length=15, verbose_name='Select Pet Type')),
                ('owner_name', models.CharField(max_length=255, verbose_name='Owner Name')),
                ('owner_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Owner Address')),
                ('owner_phone_number', models.CharField(default='', max_length=11, verbose_name='phone')),
            ],
        ),
        migrations.CreateModel(
            name='PatientAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_start_time', models.DateTimeField(verbose_name='Appointment start time')),
                ('appointment_end_time', models.DateTimeField(verbose_name='Appointment end time')),
                ('description', models.CharField(max_length=1024, verbose_name='Enter description')),
                ('payment_type', models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('BITCOIN', 'BITCOIN')], default='USD', max_length=15, verbose_name='Select payment Type')),
                ('paid_amount', models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Enter amount paid')),
                ('unpaid_amount', models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Enter unpaid amount')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Enter Total amount')),
            ],
        ),
    ]
