# Generated by Django 4.0.6 on 2022-08-05 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientappointment',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Enter amount paid'),
        ),
        migrations.AlterField(
            model_name='patientappointment',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Enter Total amount'),
        ),
        migrations.AlterField(
            model_name='patientappointment',
            name='unpaid_amount',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Enter unpaid amount'),
        ),
    ]
