# Generated by Django 4.0.6 on 2022-08-11 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_patientappointment_patient_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientappointment',
            name='patient_id',
        ),
        migrations.AddField(
            model_name='patientappointment',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pets.patient'),
        ),
    ]
