# Generated by Django 4.0.6 on 2022-07-26 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_patientappointment_alter_patient_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientappointment',
            name='pet_type',
        ),
        migrations.AddField(
            model_name='patientappointment',
            name='paynment_type',
            field=models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('BITCOIN', 'BITCOIN')], default='USD', max_length=15, verbose_name='Select paynment Type'),
        ),
    ]
