# Generated by Django 4.0.6 on 2022-07-26 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_remove_patientappointment_pet_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientappointment',
            name='paynment_type',
        ),
        migrations.AddField(
            model_name='patientappointment',
            name='payment_type',
            field=models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('BITCOIN', 'BITCOIN')], default='USD', max_length=15, verbose_name='Select payment Type'),
        ),
    ]
