# Generated by Django 4.0.6 on 2022-07-26 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0005_alter_patientappointment_total_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientappointment',
            name='appointment_end_time',
            field=models.DateTimeField(verbose_name='Appointment end time'),
        ),
        migrations.AlterField(
            model_name='patientappointment',
            name='appointment_start_time',
            field=models.DateTimeField(verbose_name='Appointment start time'),
        ),
    ]
