# Generated by Django 4.0.6 on 2022-07-27 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0006_alter_patientappointment_appointment_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='patientappointment',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
