# Generated by Django 4.0.6 on 2022-07-27 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0007_alter_patient_id_alter_patientappointment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientappointment',
            name='patient_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pets.patient'),
        ),
    ]
